package com.example.projects.example.entities;

import com.example.projects.example.util.Operation;

import javax.persistence.*;

/**
 * Created by Mike on 9/4/2016.
 */
@Entity  // An Entity is an object that will be translated through the ORM (Object-Relational Mapping) into the database
@Table(schema = "dbo", name = "exampletable")  // This tells Spring/Hibernate which table this Entity represents
public class AnswerEntity {  // Again, Entities, Dtos, and POJO's should only contain data, no business logic

    @Id  // Mark this field as the primary key of the table
    @Column(name="pk")  // The corresponding column in the table
    @GeneratedValue(strategy=GenerationType.IDENTITY)  // Let Spring/Hibernate know that this value is generated by the database automatically
    private Integer id;

    @Column(name="FirstParam")
    private int firstParam;

    @Column(name="SecondParam")
    private int secondParam;

    @Column(name="Answer")
    private int value;

    @Column(name = "Operation")
    @Enumerated(EnumType.STRING)  // Tell Spring/Hibernate to use the String name of the Enum, not it's ordinal (ordinal = integer index in the list of values)
    private Operation operation;

    public AnswerEntity() {
    }

    public AnswerEntity(int firstParam, int secondParam, int value, Operation operation) {
        this.firstParam = firstParam;
        this.secondParam = secondParam;
        this.operation = operation;
        this.value = value;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public int getFirstParam() {
        return firstParam;
    }

    public void setFirstParam(int firstParam) {
        this.firstParam = firstParam;
    }

    public int getSecondParam() {
        return secondParam;
    }

    public void setSecondParam(int secondParam) {
        this.secondParam = secondParam;
    }

    public int getValue() {
        return value;
    }

    public void setValue(int value) {
        this.value = value;
    }

    public Operation getOperation() {
        return operation;
    }

    public void setOperation(Operation operation) {
        this.operation = operation;
    }

}
